"use client";

// Web sound-effect loader. "Sound effects from the web" means: instead of
// only the tiny on-the-fly Web-Audio synth, the app fetches real, layered SFX
// files served over HTTP.
//
// Source priority per effect (first that loads wins):
//   1. Remote CDN URLs — optional, owner-configured (SFX_REMOTE). Empty by
//      default so the app ships self-contained; drop in a richer library here.
//   2. Bundled files under /public/sfx/*.wav — generated by
//      scripts/generate-sfx.js, cached by the service worker, work offline.
//   3. The synthesized bank (renderSfxPreview) — always succeeds, so a missing
//      file or a blocked/offline fetch NEVER breaks a render.
//
// Everything degrades gracefully: the render pipeline always gets a usable
// audio blob, whatever the network is doing.
import { renderSfxPreview, type SfxType } from "./audio-cinema";

// Owner-configurable remote library. Leave empty to use the bundled files.
// Any URL added here is tried before the local copy — e.g. a CC0 SFX CDN.
// (Kept empty by default: shipping URLs we can't guarantee stay live would
// just add latency before the local fallback every render.)
export const SFX_REMOTE: Partial<Record<SfxType, string[]>> = {};

// Bundled local files (served from the app origin → cached by the SW).
const LOCAL: Record<SfxType, string> = {
  whoosh: "/sfx/whoosh.wav",
  impact: "/sfx/impact.wav",
  glitch: "/sfx/glitch.wav",
  riser: "/sfx/riser.wav",
};

export type SfxManifest = Record<SfxType, string[]>;

export function defaultManifest(): SfxManifest {
  const types: SfxType[] = ["whoosh", "impact", "glitch", "riser"];
  const m = {} as SfxManifest;
  for (const t of types) m[t] = [...(SFX_REMOTE[t] ?? []), LOCAL[t]];
  return m;
}

export interface ResolvedSfx {
  blob: Blob;
  source: string; // the URL that loaded, or "synth"
}

// Try each candidate URL in order; fall back to the synthesized bank. This is
// the un-cached primitive — used directly by tests to exercise both the real
// fetch path and the fallback deterministically.
export async function resolveSfxBlob(type: SfxType, urls: string[]): Promise<ResolvedSfx> {
  for (const url of urls) {
    try {
      const res = await fetch(url, { cache: "force-cache" });
      if (!res.ok) continue;
      const blob = await res.blob();
      // Guard against an HTML error page slipping through as a "successful"
      // fetch: a real SFX file is well over a few hundred bytes of audio.
      if (blob.size > 256 && !blob.type.includes("html")) {
        return { blob, source: url };
      }
    } catch {
      // network/CORS/offline — try the next candidate
    }
  }
  return { blob: await renderSfxPreview(type), source: "synth" };
}

// Cached public API: resolve once per effect per session.
const cache = new Map<SfxType, Promise<ResolvedSfx>>();

export function loadSfx(type: SfxType): Promise<ResolvedSfx> {
  if (!cache.has(type)) {
    const manifest = defaultManifest();
    cache.set(type, resolveSfxBlob(type, manifest[type]));
  }
  return cache.get(type)!;
}

// For a full transition SFX schedule, load every referenced effect's blob (in
// parallel, de-duplicated by the cache) and attach it to each cue. The result
// feeds straight into mixTimeline, which plays the blob when present and only
// synthesizes when it's absent.
export async function resolveTransitionSfx(
  cues: { time: number; type: SfxType }[]
): Promise<{ time: number; type: SfxType; blob: Blob }[]> {
  const unique = [...new Set(cues.map((c) => c.type))];
  const loaded = new Map<SfxType, Blob>();
  await Promise.all(
    unique.map(async (t) => {
      const r = await loadSfx(t);
      loaded.set(t, r.blob);
    })
  );
  return cues.map((c) => ({ time: c.time, type: c.type, blob: loaded.get(c.type)! }));
}

// Test/diagnostics: which source each effect resolves to right now.
export async function sfxSourceReport(): Promise<Record<SfxType, string>> {
  const types: SfxType[] = ["whoosh", "impact", "glitch", "riser"];
  const out = {} as Record<SfxType, string>;
  for (const t of types) out[t] = (await loadSfx(t)).source;
  return out;
}
