# ViralEdit AI — production image.
#
# WHY THIS EXISTS: /api/download shells out to yt-dlp (a Python binary) with
# a persistent filesystem and a real OS process. That combination does not
# exist on serverless platforms (Vercel, Netlify Functions, Cloudflare
# Workers) — they give you neither arbitrary binaries nor guaranteed
# persistent /tmp across invocations. This image targets any host that runs
# a plain container: Railway, Render, Fly.io, a VPS, or your own Kubernetes.
#
# If you don't need the "paste a link" download feature, the app still runs
# fine on serverless — just expect that one route to fail there.

FROM node:20-slim AS base

# yt-dlp needs python3; ffmpeg is NOT required server-side (all video
# processing happens in the browser via WASM) but yt-dlp's merge step
# benefits from having a system ffmpeg available as a fallback muxer.
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    ffmpeg \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install yt-dlp from PyPI (more reliably updated than distro packages —
# yt-dlp ships frequent releases to keep up with platform changes)
RUN pip3 install --no-cache-dir --break-system-packages yt-dlp

WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# `COPY . .` overlays the plain repo's public/ (ffmpeg WASM is gitignored,
# generated by postinstall) on top of what deps' `npm ci` produced in a
# DIFFERENT stage filesystem — re-run the generator explicitly so the
# core actually ends up in this stage's public/ before the build copies it.
RUN node scripts/copy-ffmpeg-core.js
RUN npm run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# healthcheck hits the home page — cheap and confirms the server (not just
# the process) is actually serving requests
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD curl -f http://localhost:3000/home || exit 1

CMD ["node", "server.js"]
